### ISSUE TITLE
How to read binary values

### ISSUE THREAD

**Issue by ProjectSky** [Ochii/csovxl#1]
* I tried to use the tool but got some unknown data

![image](https://user-images.githubusercontent.com/16351827/69939939-ffe94780-151b-11ea-814d-cf0c0811c018.png)

* i upload example file: [vxl.zip](https://github.com/L-Leite/csovxl/files/3910013/vxl.zip)

**Comment by lateleite** [comment]
That's not unreadable data, those values are in binary.

This is what I understood from reading the values in [global_data]:
The first byte is the value type, followed by the value's data itself
I found these value types:
- 1 - integer: the value's data is 4 bytes long
- 3 - color: the value's data is an array of 2 bytes integers with 3 elements (red, green, blue)
- 4 - unknown (used in gamemode,  playtime, playernum, ...), 7 bytes long

**Comment by ProjectSky** [comment]
> That's not unreadable data, those values are in binary.

ok, thx for the explanation.
